import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getCostEstimations } from '../../../api/presales.api';
import { Plus, Search } from 'lucide-react';
import { useAuth } from '../../../contexts/AuthContext';

export const CostEstList = () => {
  const navigate = useNavigate();
  const { hasPermission } = useAuth();
  const [estimates, setEstimates] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [search, setSearch] = useState('');

  useEffect(() => {
    getCostEstimations()
      .then(res => setEstimates(res.data.data))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  const filteredEstimates = estimates.filter(e => 
    e.customerName?.toLowerCase().includes(search.toLowerCase()) ||
    e.createdByName?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="lead-list animate-fade">
      <div className="page-header">
        <div className="page-header-left">
          <h1 className="page-title">Commercial Cost Estimations</h1>
          <p className="page-subtitle">Configure engineering material base, implementation costs, margins, and taxation.</p>
        </div>
        {hasPermission('mod_ps_costing', 'create') && (
          <div className="page-actions">
            <button className="btn btn-primary" onClick={() => navigate('/presales/costing/new')}>
              <Plus size={16} /> Generate Cost Estimate
            </button>
          </div>
        )}
      </div>

      {loading ? (
        <div className="flex-center" style={{ minHeight: '30vh' }}>
          <div className="spinner" style={{ borderColor: 'rgba(37,99,235,.2)', borderTopColor: '#2563EB', width: 30, height: 30 }} />
        </div>
      ) : (
        <div className="card table-wrapper">
          <div className="table-toolbar">
            <div className="table-search">
              <Search size={16} style={{ color: 'var(--color-text-muted)' }} />
              <input
                type="text"
                placeholder="Search by customer or estimator..."
                value={search}
                onChange={e => setSearch(e.target.value)}
              />
            </div>
          </div>

          {filteredEstimates.length === 0 ? (
            <div className="card text-center" style={{ padding: '40px 20px', color: '#64748B', border: 'none' }}>
              No costing estimates matching your filters.
            </div>
          ) : (
            <table className="table">
              <thead>
                <tr>
                  <th>Customer Name</th>
                  <th>Material Cost</th>
                  <th>Implementation Cost</th>
                  <th>Margin %</th>
                  <th>GST %</th>
                  <th>Final Price (Incl. Tax)</th>
                  <th>Generated By</th>
                </tr>
              </thead>
              <tbody>
                {filteredEstimates.map(e => {
                  const implementationTotal = e.labourCost + e.transportationCost + e.civilCost + e.installationCost + e.overheadCost;
                  return (
                    <tr key={e.id}>
                      <td style={{ fontWeight: 600 }}>{e.customerName}</td>
                      <td>₹{e.materialCost?.toLocaleString()}</td>
                      <td>₹{implementationTotal?.toLocaleString()}</td>
                      <td>{e.marginPercentage}%</td>
                      <td>{e.taxPercentage}%</td>
                      <td style={{ fontWeight: 750, color: '#10B981', fontSize: '14.5px' }}>
                        ₹{Math.round(e.finalProjectCost)?.toLocaleString()}
                      </td>
                      <td>{e.createdByName}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  );
};
