import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getSizingReports } from '../../../api/presales.api';
import { Plus, FileText, Search } from 'lucide-react';
import { useAuth } from '../../../contexts/AuthContext';

export const SizingReportList = () => {
  const navigate = useNavigate();
  const { hasPermission } = useAuth();
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [search, setSearch] = useState('');

  useEffect(() => {
    getSizingReports()
      .then(res => setReports(res.data.data))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  const filteredReports = reports.filter(r => 
    r.customerName?.toLowerCase().includes(search.toLowerCase()) ||
    r.generatedByName?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="lead-list animate-fade">
      <div className="page-header">
        <div className="page-header-left">
          <h1 className="page-title">Sizing & Generation Reports</h1>
          <p className="page-subtitle">Solar potential calculations, estimated yield factors, and performance metrics.</p>
        </div>
        {hasPermission('mod_ps_sizing', 'create') && (
          <div className="page-actions">
            <button className="btn btn-primary" onClick={() => navigate('/presales/sizing-reports/new')}>
              <Plus size={16} /> Generate Sizing Report
            </button>
          </div>
        )}
      </div>

      {loading ? (
        <div className="flex-center" style={{ minHeight: '30vh' }}>
          <div className="spinner" style={{ borderColor: 'rgba(37,99,235,.2)', borderTopColor: '#2563EB', width: 30, height: 30 }} />
        </div>
      ) : (
        <div className="card table-wrapper">
          <div className="table-toolbar">
            <div className="table-search">
              <Search size={16} style={{ color: 'var(--color-text-muted)' }} />
              <input
                type="text"
                placeholder="Search by customer or engineer..."
                value={search}
                onChange={e => setSearch(e.target.value)}
              />
            </div>
          </div>

          {filteredReports.length === 0 ? (
            <div className="card text-center" style={{ padding: '40px 20px', color: '#64748B', border: 'none' }}>
              No sizing reports matching your filters.
            </div>
          ) : (
            <table className="table">
              <thead>
                <tr>
                  <th>Customer Name</th>
                  <th>Req. Capacity</th>
                  <th>Recommended</th>
                  <th>Estimated Annual Yield</th>
                  <th>Inverter Capacity</th>
                  <th>Generated By</th>
                </tr>
              </thead>
              <tbody>
                {filteredReports.map(r => (
                  <tr key={r.id}>
                    <td style={{ fontWeight: 600 }}>{r.customerName}</td>
                    <td>{r.requiredCapacity} kWp</td>
                    <td style={{ fontWeight: 600, color: '#2563EB' }}>{r.recommendedCapacity} kWp</td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontWeight: 600 }}>
                        <FileText size={13} style={{ color: '#0EA5E9' }} />
                        {r.annualGenerationEstimate?.toLocaleString()} kWh
                      </div>
                      <div style={{ fontSize: '11px', color: '#64748B' }}>Yield: {r.estimatedYield} kWh/kWp/yr</div>
                    </td>
                    <td>{r.inverterCapacity} kW</td>
                    <td style={{ fontSize: '13px', color: '#475569' }}>{r.generatedByName}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  );
};
